/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.restoran.gui;

import com.restoran.model.DetailPesanan;
import com.restoran.model.Pesanan;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author WIN10
 */
public class EditPesananFrame extends javax.swing.JFrame {
    private Pesanan currentPesanan;
    private List<DetailPesanan> itemsToDisplay;
    
    /**
     * Creates new form EditPesananFrame
     */
    public EditPesananFrame() {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }
    
    public EditPesananFrame(Pesanan pesanan) {
        this();
        this.currentPesanan = pesanan;
        populateComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelPilihPesanan = new javax.swing.JLabel();
        jComboBoxItemPesanan = new javax.swing.JComboBox<>();
        jLabelInputKuantitas = new javax.swing.JLabel();
        jTextFieldKuantitasBaru = new java.awt.TextField();
        btnOK = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edit Pesanan");

        jLabelPilihPesanan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelPilihPesanan.setText("Pilih pesanan yang akan diedit:");

        jComboBoxItemPesanan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxItemPesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxItemPesananActionPerformed(evt);
            }
        });

        jLabelInputKuantitas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelInputKuantitas.setText("Masukkan jumlah baru untuk [Nama Menu] (saat ini: [Jumlah]):");

        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jComboBoxItemPesanan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabelPilihPesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(47, 47, 47))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldKuantitasBaru, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnOK)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancel)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelInputKuantitas)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabelPilihPesanan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxItemPesanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelInputKuantitas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldKuantitasBaru, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnOK))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void populateComboBox() {
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        itemsToDisplay = new java.util.ArrayList<>();

        if (currentPesanan != null && !currentPesanan.getDetailPesananList().isEmpty()) {
            for (DetailPesanan detail : currentPesanan.getDetailPesananList()) {
                model.addElement(String.format("%s x%d = Rp%,.0f", 
                                               detail.getMenu().getNama(), 
                                               detail.getKuantitas(), 
                                               detail.getSubTotal()));
                itemsToDisplay.add(detail);
            }
            jComboBoxItemPesanan.setModel(model);
            jComboBoxItemPesanan.setSelectedIndex(0);
        } else {
            model.addElement("Tidak ada pesanan aktif.");
            jComboBoxItemPesanan.setModel(model);
            btnOK.setEnabled(false);
            jTextFieldKuantitasBaru.setEditable(false);
        }
    }
    
    private void jComboBoxItemPesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxItemPesananActionPerformed
        int selectedIndex = jComboBoxItemPesanan.getSelectedIndex();
        if (selectedIndex >= 0 && selectedIndex < itemsToDisplay.size()) {
            DetailPesanan selectedDetail = itemsToDisplay.get(selectedIndex);
            jLabelInputKuantitas.setText(String.format("Masukkan jumlah baru untuk %s (saat ini: %d):", 
                                                        selectedDetail.getMenu().getNama(), 
                                                        selectedDetail.getKuantitas()));
            jTextFieldKuantitasBaru.setText(String.valueOf(selectedDetail.getKuantitas()));
        } else {
             jLabelInputKuantitas.setText("Masukkan jumlah baru:");
             jTextFieldKuantitasBaru.setText("");
        }
    }//GEN-LAST:event_jComboBoxItemPesananActionPerformed

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        int selectedIndex = jComboBoxItemPesanan.getSelectedIndex();
        if (selectedIndex < 0 || itemsToDisplay.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Pilih item pesanan terlebih dahulu.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        DetailPesanan detailToEdit = itemsToDisplay.get(selectedIndex);
        String kuantitasStr = jTextFieldKuantitasBaru.getText().trim();

        if (kuantitasStr.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Kuantitas tidak boleh kosong.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            int newKuantitas = Integer.parseInt(kuantitasStr);
            if (newKuantitas < 0) {
                JOptionPane.showMessageDialog(this, "Kuantitas tidak boleh negatif.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            boolean updated = currentPesanan.updateKuantitasDetailPesanan(detailToEdit, newKuantitas);

            if (updated) {
                populateComboBox();
                if (newKuantitas > 0 && selectedIndex < jComboBoxItemPesanan.getItemCount()) {
                    jComboBoxItemPesanan.setSelectedIndex(selectedIndex);
                } else if (jComboBoxItemPesanan.getItemCount() > 0) {
                    jComboBoxItemPesanan.setSelectedIndex(0);
                }

                JOptionPane.showMessageDialog(this, 
                                              String.format("Pesanan %s berhasil diupdate menjadi %d unit.", detailToEdit.getMenu().getNama(), newKuantitas), 
                                              "Pesanan Diupdate", 
                                              JOptionPane.INFORMATION_MESSAGE);
                this.dispose(); 

            } else {
                JOptionPane.showMessageDialog(this, "Gagal mengupdate pesanan.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Kuantitas tidak valid. Masukkan angka bulat.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnOKActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditPesananFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditPesananFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditPesananFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditPesananFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditPesananFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOK;
    private javax.swing.JComboBox<String> jComboBoxItemPesanan;
    private javax.swing.JLabel jLabelInputKuantitas;
    private javax.swing.JLabel jLabelPilihPesanan;
    private java.awt.TextField jTextFieldKuantitasBaru;
    // End of variables declaration//GEN-END:variables
}
