/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.restoran.gui;

import com.restoran.model.Admin;
import com.restoran.model.Menu;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author WIN10
 */
public class HapusMenuMakananFrame extends javax.swing.JFrame {
    private Admin currentAdmin;
    private List<Menu> displayedMenus;

    /**
     * Creates new form HapusMenuMakananFrame
     */
    public HapusMenuMakananFrame() {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }
    
     public HapusMenuMakananFrame(Admin admin) {
        this();
        this.currentAdmin = admin;
        populateComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelPilihMenu = new javax.swing.JLabel();
        jComboBoxDaftarMenu = new javax.swing.JComboBox<>();
        btnHapus = new javax.swing.JButton();
        btnBatal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Hapus Menu Makanan");

        jLabelPilihMenu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelPilihMenu.setText("Pilih menu yang akan dihapus:");

        jComboBoxDaftarMenu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnBatal.setText("Selesai");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelPilihMenu)
                                .addGap(0, 133, Short.MAX_VALUE))
                            .addComponent(jComboBoxDaftarMenu, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnHapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBatal)
                        .addGap(6, 6, 6)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabelPilihMenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxDaftarMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBatal)
                    .addComponent(btnHapus))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void populateComboBox() {
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        displayedMenus = new java.util.ArrayList<>();

        if (currentAdmin != null) {
            List<Menu> daftarMenu = currentAdmin.getDaftarMenuAdmin();
            if (daftarMenu.isEmpty()) {
                model.addElement("Tidak ada menu yang tersedia.");
                btnHapus.setEnabled(false);
            } else {
                for (Menu menu : daftarMenu) {
                    model.addElement(menu.getNama() + " (Rp" + menu.getHarga() + ")");
                    displayedMenus.add(menu);
                }
                btnHapus.setEnabled(true);
            }
        } else {
            model.addElement("Error: Admin tidak ditemukan.");
            btnHapus.setEnabled(false);
        }
        jComboBoxDaftarMenu.setModel(model);
    }
    
    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        int selectedIndex = jComboBoxDaftarMenu.getSelectedIndex();
        if (selectedIndex < 0 || displayedMenus.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Pilih menu yang akan dihapus.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        Menu menuToDelete = displayedMenus.get(selectedIndex);

        int confirm = JOptionPane.showConfirmDialog(this,
                "Yakin ingin menghapus menu: " + menuToDelete.getNama() + "?",
                "Konfirmasi Hapus Menu",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);

        if (confirm == JOptionPane.YES_OPTION) {
            if (currentAdmin != null) {
                boolean success = currentAdmin.hapusMenu(menuToDelete.getNama());
                if (success) {
                    JOptionPane.showMessageDialog(this, "Menu '" + menuToDelete.getNama() + "' berhasil dihapus.", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                    populateComboBox();
                    if (currentAdmin.getDaftarMenuAdmin().isEmpty()) {
                        this.dispose();
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "Gagal menghapus menu. Menu tidak ditemukan atau error penyimpanan.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Objek Admin tidak valid. Mohon login kembali.", "Error", JOptionPane.ERROR_MESSAGE);
                this.dispose();
            }
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnBatalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HapusMenuMakananFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HapusMenuMakananFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HapusMenuMakananFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HapusMenuMakananFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HapusMenuMakananFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnHapus;
    private javax.swing.JComboBox<String> jComboBoxDaftarMenu;
    private javax.swing.JLabel jLabelPilihMenu;
    // End of variables declaration//GEN-END:variables
}
