/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.restoran.gui;

import com.restoran.model.DetailPesanan;
import com.restoran.model.Pesanan;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author WIN10
 */
public class HapusPesananFrame extends javax.swing.JFrame {
    private Pesanan currentPesanan;
    private List<DetailPesanan> itemsToDisplay;

    /**
     * Creates new form HapusPesananFrame
     */
    public HapusPesananFrame() {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }
    
    public HapusPesananFrame(Pesanan pesanan) {
        this();
        this.currentPesanan = pesanan;
        populateComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelPilihPesanan = new javax.swing.JLabel();
        jComboBoxItemPesanan = new javax.swing.JComboBox<>();
        btnHapus = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Hapus Pesanan");

        jLabelPilihPesanan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelPilihPesanan.setText("Pilih pesanan yang akan dihapus:");

        jComboBoxItemPesanan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jComboBoxItemPesanan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnCancel.setText("Selesai");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxItemPesanan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelPilihPesanan)
                                .addGap(0, 48, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnHapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancel)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabelPilihPesanan)
                .addGap(18, 18, 18)
                .addComponent(jComboBoxItemPesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHapus)
                    .addComponent(btnCancel))
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        int selectedIndex = jComboBoxItemPesanan.getSelectedIndex();
        if (selectedIndex < 0 || itemsToDisplay.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Pilih item pesanan terlebih dahulu.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        DetailPesanan detailToDelete = itemsToDisplay.get(selectedIndex);

        int confirm = JOptionPane.showConfirmDialog(this,
                "Yakin ingin menghapus item: " + detailToDelete.getMenu().getNama() + " x" + detailToDelete.getKuantitas() + "?",
                "Konfirmasi Hapus",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE);

        if (confirm == JOptionPane.YES_OPTION) {
            currentPesanan.hapusDetailPesanan(detailToDelete);

            JOptionPane.showMessageDialog(this, 
                                          "Pesanan " + detailToDelete.getMenu().getNama() + " berhasil dihapus.", 
                                          "Pesanan Dihapus", 
                                          JOptionPane.INFORMATION_MESSAGE);
            populateComboBox(); 

            if (currentPesanan.getDetailPesananList().isEmpty()) {
                this.dispose(); 
            } else {
                 if(jComboBoxItemPesanan.getItemCount() > 0) {
                     jComboBoxItemPesanan.setSelectedIndex(0);
                 }
            }
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    
    private void populateComboBox() {
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        itemsToDisplay = new java.util.ArrayList<>();

        if (currentPesanan != null && !currentPesanan.getDetailPesananList().isEmpty()) {
            for (DetailPesanan detail : currentPesanan.getDetailPesananList()) {
                model.addElement(String.format("%s x%d = Rp%,.0f", 
                                               detail.getMenu().getNama(), 
                                               detail.getKuantitas(), 
                                               detail.getSubTotal()));
                itemsToDisplay.add(detail);
            }
            jComboBoxItemPesanan.setModel(model);
            jComboBoxItemPesanan.setSelectedIndex(0);
        } else {
            model.addElement("Tidak ada pesanan aktif.");
            jComboBoxItemPesanan.setModel(model);
            btnHapus.setEnabled(false);
        }
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HapusPesananFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HapusPesananFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HapusPesananFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HapusPesananFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HapusPesananFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnHapus;
    private javax.swing.JComboBox<String> jComboBoxItemPesanan;
    private javax.swing.JLabel jLabelPilihPesanan;
    // End of variables declaration//GEN-END:variables
}
