/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.restoran.gui;

import com.restoran.model.DetailPesanan;
import com.restoran.model.Pesanan;
import javax.swing.JFrame;

/**
 *
 * @author WIN10
 */
public class LihatPesananSayaFrame extends javax.swing.JFrame {
    private Pesanan pesananDilihat;
    /**
     * Creates new form LihatPesananSayaFrame
     */
    public LihatPesananSayaFrame() {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }
    
    public LihatPesananSayaFrame(Pesanan pesanan) {
        this();
        this.pesananDilihat = pesanan;
        displayPesananDetails();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelJudulPesanan = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDetailPesanan = new java.awt.TextArea();
        jLabelTotalPesanan = new javax.swing.JLabel();
        btnOK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Detail Pesanan");

        jLabelJudulPesanan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelJudulPesanan.setText("Pesanan Anda :");

        jTextAreaDetailPesanan.setEditable(false);
        jTextAreaDetailPesanan.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jScrollPane1.setViewportView(jTextAreaDetailPesanan);

        jLabelTotalPesanan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelTotalPesanan.setText("Total Pesanan : Rp0");

        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTotalPesanan)
                            .addComponent(jLabelJudulPesanan)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnOK)
                        .addGap(110, 110, 110))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabelJudulPesanan)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelTotalPesanan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnOK)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnOKActionPerformed

    /**
     * @param args the command line arguments
     */
    private void displayPesananDetails() {
        StringBuilder sb = new StringBuilder();
        sb.append("===========================\n");
        sb.append("Pesanan Anda:\n");
        sb.append("===========================\n");

        if (pesananDilihat == null || pesananDilihat.getDetailPesananList().isEmpty()) {
            sb.append("\nBelum ada pesanan yang dibuat.\n");
        } else {
            int itemNo = 1;
            for (DetailPesanan detail : pesananDilihat.getDetailPesananList()) {
                sb.append(String.format("%d. %s x%d = Rp%,.0f%n",
                                        itemNo++, 
                                        detail.getMenu().getNama(), 
                                        detail.getKuantitas(), 
                                        detail.getSubTotal()));
            }
        }
        sb.append("===========================\n");
        jTextAreaDetailPesanan.setText(sb.toString());

        if (pesananDilihat != null) {
            jLabelTotalPesanan.setText(String.format("Total Pesanan: Rp%,.0f", pesananDilihat.getTotalHarga()));
        } else {
            jLabelTotalPesanan.setText("Total Pesanan: Rp0");
        }
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LihatPesananSayaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LihatPesananSayaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LihatPesananSayaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LihatPesananSayaFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LihatPesananSayaFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOK;
    private javax.swing.JLabel jLabelJudulPesanan;
    private javax.swing.JLabel jLabelTotalPesanan;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.TextArea jTextAreaDetailPesanan;
    // End of variables declaration//GEN-END:variables
}
