package com.restoran.gui;

import com.restoran.gui.LihatMenuFrame;
import com.restoran.gui.LoginFrame;
import com.restoran.gui.PesanMakananFrame;
import com.restoran.model.Admin;
import com.restoran.model.LaporanPenjualanManager;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ADVAN
 */
import com.restoran.model.Pelanggan;
import com.restoran.model.Pesanan;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.awt.event.WindowAdapter; // <--- Pastikan import ini ada
import java.awt.event.WindowEvent;

public class MenuPelangganFrame extends javax.swing.JFrame {
    private Pelanggan pelanggan;
    private Pesanan currentPesanan;
    
    /**
     * Creates new form MenuPelangganFrame
     */
    public MenuPelangganFrame() {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.currentPesanan = new Pesanan();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton9 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnPesanMakanan = new javax.swing.JButton();
        btnPilihMetodePembayaran = new javax.swing.JButton();
        btnLihatMenu = new javax.swing.JButton();
        btnLihatPesananSaya = new javax.swing.JButton();
        btnOrderFixCetakStruk = new javax.swing.JButton();
        btnEditPesanan = new javax.swing.JButton();
        btnHapusPesanan = new javax.swing.JButton();
        btnKembali = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        jButton9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton9.setText("Hapus Pesanan");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pelanggan");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Menu Pelanggan");

        btnPesanMakanan.setText("Pesan Makanan");
        btnPesanMakanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesanMakananActionPerformed(evt);
            }
        });

        btnPilihMetodePembayaran.setText("Pilih Metode Pembayaran");
        btnPilihMetodePembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPilihMetodePembayaranActionPerformed(evt);
            }
        });

        btnLihatMenu.setText("Lihat Menu");
        btnLihatMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLihatMenuActionPerformed(evt);
            }
        });

        btnLihatPesananSaya.setText("Lihat Pesanan Saya");
        btnLihatPesananSaya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLihatPesananSayaActionPerformed(evt);
            }
        });

        btnOrderFixCetakStruk.setText("Order Fix & Cetak Struk");
        btnOrderFixCetakStruk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderFixCetakStrukActionPerformed(evt);
            }
        });

        btnEditPesanan.setText("Edit Pesanan");
        btnEditPesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditPesananActionPerformed(evt);
            }
        });

        btnHapusPesanan.setText("Hapus Pesanan");
        btnHapusPesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusPesananActionPerformed(evt);
            }
        });

        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(176, 176, 176))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(btnEditPesanan)
                        .addGap(18, 18, 18)
                        .addComponent(btnHapusPesanan)
                        .addGap(18, 18, 18)
                        .addComponent(btnKembali)
                        .addGap(18, 18, 18)
                        .addComponent(btnExit)
                        .addContainerGap(45, Short.MAX_VALUE))
                    .addComponent(btnPilihMetodePembayaran, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLihatPesananSaya, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnOrderFixCetakStruk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLihatMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPesanMakanan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(btnPesanMakanan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLihatMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLihatPesananSaya, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPilihMetodePembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnOrderFixCetakStruk, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHapusPesanan)
                    .addComponent(btnKembali)
                    .addComponent(btnExit)
                    .addComponent(btnEditPesanan))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLihatMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLihatMenuActionPerformed
        LihatMenuFrame lihatMenuFrame = new LihatMenuFrame();
        lihatMenuFrame.setVisible(true);
    }//GEN-LAST:event_btnLihatMenuActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void btnPesanMakananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesanMakananActionPerformed
        PesanMakananFrame pesanMakananFrame = new PesanMakananFrame(currentPesanan);
        pesanMakananFrame.setVisible(true);
        
        pesanMakananFrame.addWindowListener(new java.awt.event.WindowAdapter() {
        @Override
        public void windowClosed(java.awt.event.WindowEvent windowEvent) {
            Pesanan pesananYangDibuat = pesanMakananFrame.getPesanan();
            if (pesananYangDibuat != null && !pesananYangDibuat.getDetailPesananList().isEmpty()) {
                currentPesanan = pesananYangDibuat;
                JOptionPane.showMessageDialog(null, 
                                              "Pesanan berhasil ditambahkan. Total item: " + currentPesanan.getDetailPesananList().size(), 
                                              "Pesanan Diperbarui", 
                                              JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, 
                                              "Tidak ada item yang ditambahkan ke pesanan.", 
                                              "Peringatan", 
                                              JOptionPane.WARNING_MESSAGE);
            }
        }
    });
    }//GEN-LAST:event_btnPesanMakananActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        LoginFrame loginFrame = new LoginFrame();
        loginFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void btnLihatPesananSayaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLihatPesananSayaActionPerformed
        LihatPesananSayaFrame lihatPesananSayaFrame = new LihatPesananSayaFrame(currentPesanan);
        lihatPesananSayaFrame.setVisible(true);
    }//GEN-LAST:event_btnLihatPesananSayaActionPerformed

    private void btnPilihMetodePembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPilihMetodePembayaranActionPerformed
        if (currentPesanan == null || currentPesanan.getDetailPesananList().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Belum ada pesanan aktif untuk dipilih metode pembayarannya.", "Info Pembayaran", JOptionPane.INFORMATION_MESSAGE);
        return;
    }

    PilihMetodePembayaranFrame pilihMetodeFrame = new PilihMetodePembayaranFrame(currentPesanan);
    pilihMetodeFrame.setVisible(true);

    pilihMetodeFrame.addWindowListener(new WindowAdapter() {
        @Override
        public void windowClosed(WindowEvent windowEvent) {
            if (!pilihMetodeFrame.isCancelled()) {
                String metodeTerpilih = pilihMetodeFrame.getSelectedMetode();
                if (metodeTerpilih != null) {
                    currentPesanan.setMetodePembayaran(metodeTerpilih);

                    JOptionPane.showMessageDialog(null,
                                                  "Metode pembayaran terpilih: " + metodeTerpilih, 
                                                  "Metode Pembayaran", 
                                                  JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(null, "Tidak ada metode pembayaran yang dipilih.", "Peringatan", JOptionPane.WARNING_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Pemilihan metode pembayaran dibatalkan.", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    });
    }//GEN-LAST:event_btnPilihMetodePembayaranActionPerformed

    private void btnEditPesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditPesananActionPerformed
        if (currentPesanan == null || currentPesanan.getDetailPesananList().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Belum ada pesanan untuk diedit.", "Info Edit Pesanan", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        EditPesananFrame editPesananFrame = new EditPesananFrame(currentPesanan);
        editPesananFrame.setVisible(true);

        editPesananFrame.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent windowEvent) {
                if (currentPesanan != null && !currentPesanan.getDetailPesananList().isEmpty()) {
                    JOptionPane.showMessageDialog(null,
                                              "Pesanan berhasil diupdate. Total item saat ini: " + currentPesanan.getDetailPesananList().size() + " item.",
                                              "Pesanan Diupdate",
                                              JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(null,
                                              "Pesanan mungkin kosong atau item dihapus semua.",
                                              "Pesanan Diupdate",
                                              JOptionPane.WARNING_MESSAGE);
                }
            }
        });
    }//GEN-LAST:event_btnEditPesananActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnHapusPesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusPesananActionPerformed
        if (currentPesanan == null || currentPesanan.getDetailPesananList().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Belum ada pesanan untuk dihapus.", "Info Hapus Pesanan", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        HapusPesananFrame hapusPesananFrame = new HapusPesananFrame(currentPesanan);
        hapusPesananFrame.setVisible(true);

        hapusPesananFrame.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosed(java.awt.event.WindowEvent windowEvent) {
                if (currentPesanan != null && !currentPesanan.getDetailPesananList().isEmpty()) {
                    JOptionPane.showMessageDialog(null,
                                              "Pesanan berhasil diupdate. Sisa item: " + currentPesanan.getDetailPesananList().size() + " item.",
                                              "Pesanan Diupdate",
                                              JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(null,
                                              "Semua item pesanan telah dihapus.",
                                              "Pesanan Kosong",
                                              JOptionPane.INFORMATION_MESSAGE);
                }
            }
        });
    }//GEN-LAST:event_btnHapusPesananActionPerformed

    private void btnOrderFixCetakStrukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderFixCetakStrukActionPerformed
        if (currentPesanan == null || currentPesanan.getDetailPesananList().isEmpty()) {
        JOptionPane.showMessageDialog(this, "Belum ada item dalam pesanan.", "Error Finalisasi", JOptionPane.ERROR_MESSAGE);
        return;
    }
    if (currentPesanan.getMetodePembayaran().equals("Belum Dipilih")) {
        JOptionPane.showMessageDialog(this, "Pilih metode pembayaran terlebih dahulu.", "Error Finalisasi", JOptionPane.ERROR_MESSAGE);
        return;
    }
    if (currentPesanan.isFixed()) {
        JOptionPane.showMessageDialog(this, "Pesanan ini sudah difinalisasi dan struk sudah dicetak.", "Info Finalisasi", JOptionPane.INFORMATION_MESSAGE);
        return;
    }

    currentPesanan.setFixed(true);
    currentPesanan.setStatusPesanan("Selesai");

    boolean successSaveReport = LaporanPenjualanManager.tulisStrukString(currentPesanan.generateLaporanString());
    if (!successSaveReport) {
        JOptionPane.showMessageDialog(this, "Gagal menyimpan laporan penjualan.", "Error File", JOptionPane.ERROR_MESSAGE);
    }

    StrukPembayaranFrame strukFrame = new StrukPembayaranFrame(currentPesanan);
    strukFrame.setVisible(true);
    strukFrame.addWindowListener(new WindowAdapter() {
        @Override
        public void windowClosed(WindowEvent windowEvent) {
            JOptionPane.showMessageDialog(null, 
                                          "Pesanan telah selesai dan struk dicetak. Data pesanan Anda telah direset.", 
                                          "Order Selesai", 
                                          JOptionPane.INFORMATION_MESSAGE);
            currentPesanan = new Pesanan(); 
        }
    });
    }//GEN-LAST:event_btnOrderFixCetakStrukActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPelangganFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPelangganFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPelangganFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPelangganFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditPesanan;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnHapusPesanan;
    private javax.swing.JButton btnKembali;
    private javax.swing.JButton btnLihatMenu;
    private javax.swing.JButton btnLihatPesananSaya;
    private javax.swing.JButton btnOrderFixCetakStruk;
    private javax.swing.JButton btnPesanMakanan;
    private javax.swing.JButton btnPilihMetodePembayaran;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}