/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.restoran.gui;

import com.restoran.model.Admin;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author WIN10
 */
public class TambahMenuFrame extends javax.swing.JFrame {
    private Admin currentAdmin;

    /**
     * Creates new form TambahMenuFrame
     */
    public TambahMenuFrame() {
        initComponents();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }
    
    public TambahMenuFrame(Admin admin) {
        this(); 
        this.currentAdmin = admin;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNamaMenu = new javax.swing.JLabel();
        jTextFieldNamaMenu = new java.awt.TextField();
        jLabelHargaMenu = new javax.swing.JLabel();
        jTextFieldHargaMenu = new java.awt.TextField();
        btnOK = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Input");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabelNamaMenu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelNamaMenu.setText("Nama Makanan Baru :");

        jTextFieldNamaMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNamaMenuActionPerformed(evt);
            }
        });

        jLabelHargaMenu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabelHargaMenu.setText("Harga Makanan (Rp) :");

        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldHargaMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldNamaMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelHargaMenu)
                            .addComponent(jLabelNamaMenu)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(btnOK)
                                .addGap(18, 18, 18)
                                .addComponent(btnCancel)))
                        .addGap(0, 50, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabelNamaMenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNamaMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jLabelHargaMenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldHargaMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnOK))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNamaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNamaMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNamaMenuActionPerformed

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        String namaMenu = jTextFieldNamaMenu.getText().trim();
        String hargaMenuStr = jTextFieldHargaMenu.getText().trim();

    if (namaMenu.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Nama menu tidak boleh kosong.", "Input Error", JOptionPane.ERROR_MESSAGE);
        return;
    }
    if (namaMenu.contains(";")) {
        JOptionPane.showMessageDialog(this, "Nama menu tidak boleh mengandung karakter ';'.", "Input Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    if (hargaMenuStr.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Harga menu tidak boleh kosong.", "Input Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    try {
        int hargaMenu = Integer.parseInt(hargaMenuStr);
        if (hargaMenu < 0) {
            JOptionPane.showMessageDialog(this, "Harga tidak boleh negatif.", "Error Harga", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (currentAdmin != null) {
            boolean sukses = currentAdmin.tambahMenu(namaMenu, hargaMenu);
            if (sukses) {
                JOptionPane.showMessageDialog(this, "Menu '" + namaMenu + "' berhasil ditambahkan.", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Gagal menambahkan menu. Kemungkinan nama menu sudah ada.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Objek Admin tidak ditemukan. Mohon login kembali.", "Error", JOptionPane.ERROR_MESSAGE);
            new LoginFrame().setVisible(true);
            this.dispose();
        }

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Harga tidak valid. Masukkan angka bulat.", "Input Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnOKActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TambahMenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TambahMenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TambahMenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TambahMenuFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TambahMenuFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOK;
    private javax.swing.JLabel jLabelHargaMenu;
    private javax.swing.JLabel jLabelNamaMenu;
    private java.awt.TextField jTextFieldHargaMenu;
    private java.awt.TextField jTextFieldNamaMenu;
    // End of variables declaration//GEN-END:variables
}
